[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
