[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bundle exec rails db:create db:migrate && bundle exec puma -C config/puma.rb"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
